data:
  dataset_id: uci_har
  scv_group_index: 0
  datasets_dir: datasets

model:
  architecure: cae
  size_spect: 32
  num_channels_spect: 18
  size_latent: 4
  num_channels_latent: 24
  embedding_dim: 32

train:
  batch_size: 128
  num_epochs: 100
  learning_rate: 1e-3
  patience: 5
  seed: 0

wandb:
  project: latent