data:
  dataset_id: uci_har
  scv_group_index: 0
  datasets_dir: datasets

model:
  architecure: cae
  spect_n_channels: 18
  latent_n_channels: 24
  latent_size: 4

train:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1e-3
  patience: 5
  seed: 0

wandb:
  project: test # autoencoder