defaults:
  - submitit_slurm

partition: normal 
nodes: 1
tasks_per_node: 1
gpus_per_node: 1
timeout_min: 180

setup:
  - echo "Preparing dataset ${data.dataset_id}"
  - if [ ! -f ${data.datasets_dir}/${data.dataset_id}.tgz ]; then tar -cvzf ${data.datasets_dir}/${data.dataset_id}.tgz -C ${data.datasets_dir} ${data.dataset_id}; fi
  - echo "Extracting dataset ${data.dataset_id} into $TMPDIR/${data.datasets_dir}"
  - mkdir -p $TMPDIR/${data.datasets_dir} 
  - tar -C $TMPDIR/${data.datasets_dir} -xvzf ${data.datasets_dir}/${data.dataset_id}.tgz
  - export DATASETS_DIR=$TMPDIR/${data.datasets_dir}